### ISSUE TITLE
你好...我在使用示例代码后转发正常,但是如何在返回数据后再发回给请求发起的页面??

### ISSUE THREAD

**Issue by varyuanye** [laomu1988/koa2-proxy#1]
在示例中的on('start'),之后转发是正常的,同时end事件中打印ctx.response.body.toString()同样是正常的,但是这个end事件之后并没有将返回的结果转发回请求的页面....请问这个如何解决

**Comment by laomu1988** [comment]
能贴下代码吗？

**Comment by jane-** [comment]
谢谢  ，但是我现在还没弄好。bnjs这个是不是一个插件，我贴到代码里面报错，等我整理一下

**Comment by jane-** [comment]
https://www.googleapis.com/qpxExpress/v1/trips/search?key=myApiKey
    ctx.request.host = 'www.googleapis.com';
    ctx.request.path="//qpxExpress/v1/trips/search"
    ctx.request.querystring="key=myApiKey"
    ctx.request.body={
      "request": {
        "slice": [
          {
            "origin": "ZRH",
            "destination": "DUS",
            "date": "2014-12-02"
          }
        ],
        "passengers": {
          "adultCount": 1,
          "infantInLapCount": 0,
          "infantInSeatCount": 0,
          "childCount": 0,
          "seniorCount": 0
        },
        "solutions": 2,
        "refundable": false
      }
    }
  // var url = ctx.request.url;
  // ctx.request.host = 'www.appollo.h5.me:8081';
  // ctx.request.method = 'post';
  // ctx.request.path="/api/"
  // // console.log( ctx.request)
  // ctx.request.querystring="url=https://ceshi.api.vipsouq.net"+url
  // // ctx.request.protocol = 'https';
  //
  // // console.log(ctx,"***99999*****", ctx.request.body);
});
https://stackoverflow.com/questions/27190447/pass-json-to-http-post-request
这个问题跟我的这个差不多， 我把它改成网上可以访问的接口，麻烦你看看

**Comment by jane-** [comment]
proxy.when(/api(.*)/, function(ctx) {

  https://www.googleapis.com/qpxExpress/v1/trips/search?key=myApiKey
    ctx.request.host = 'www.googleapis.com';
    ctx.request.path="//qpxExpress/v1/trips/search"
    ctx.request.querystring="key=myApiKey"
    ctx.request.body={
      "request": {
        "slice": [
          {
            "origin": "ZRH",
            "destination": "DUS",
            "date": "2014-12-02"
          }
        ],
        "passengers": {
          "adultCount": 1,
          "infantInLapCount": 0,
          "infantInSeatCount": 0,
          "childCount": 0,
          "seniorCount": 0
        },
        "solutions": 2,
        "refundable": false
      }
    }
  // var url = ctx.request.url;
  // ctx.request.host = 'www.appollo.h5.me:8081';
  // ctx.request.method = 'post';
  // ctx.request.path="/api/"
  // // console.log( ctx.request)
  // ctx.request.querystring="url=https://ceshi.api.vipsouq.net"+url
  // // ctx.request.protocol = 'https';
  //
  // // console.log(ctx,"***99999*****", ctx.request.body);
});

https://stackoverflow.com/questions/27190447/pass-json-to-http-post-request
这个问题跟我的差不多，我把它改成google的接口， 麻烦你看看

**Comment by laomu1988** [comment]
https://github.com/laomu1988/koa2-proxy/issues/2
@jane- 请注意header的content-type标记会影响body的解析, 这里你可以加上。。 另外，代码贴错位置了
ctx.request.header['content-type'] = 'application/json';

**Comment by jane-** [comment]
多谢，可以正常工作啦，

**Comment by jane-** [comment]
不好意思，我还想问下如果是图片
let formDataImg = new FormData();
formDataImg.append('multipart/form-data', blob, oFiles[0].name);
 formDataImg.append('accessToken', _that.token);
ajax 这样的代码，代理服务器需要设置什么东西呢。

**Comment by laomu1988** [comment]
按正常表单提交即可， 代理服务器支持文件转发， 无需特殊配置

**Comment by jane-** [comment]
不好意思还是这个问题， 我虽然设置了  ctx.request.header['content-type'] = 'application/json';但是发送到服务器上还是form类型
proxy.when(/api(.*)/, function(ctx) {

  https://www.googleapis.com/qpxExpress/v1/trips/search?key=myApiKey
    ctx.request.host = 'www.googleapis.com';

  ctx.request.path="//qpxExpress/v1/trips/search"
  ctx.request.querystring="key=myApiKey"
  ctx.request.protocol = 'https';
  ctx.request.header['content-type'] = 'application/json';
  ctx.request.body={
    "request": {
      "slice": [
        {
          "origin": "ZRH",
          "destination": "DUS",
          "date": "2014-12-02"
        }
      ],
      "passengers": {
        "adultCount": 1,
        "infantInLapCount": 0,
        "infantInSeatCount": 0,
        "childCount": 0,
        "seniorCount": 0
      },
      "solutions": 2,
      "refundable": false
    }
  }
// var url = ctx.request.url;
// ctx.request.host = 'www.appollo.h5.me:8081';
// ctx.request.method = 'post';
// ctx.request.path="/api/"
// // console.log( ctx.request)
// ctx.request.querystring="url=https://ceshi.api.vipsouq.net"+url
// // ctx.request.protocol = 'https';
//
// // console.log(ctx,"99999**", ctx.request.body);
});

麻烦你看看
