### ISSUE TITLE
能够把一个请求转发给多个服务吗？

### ISSUE THREAD

**Issue by YSHIDM** [laomu1988/koa2-proxy#10]
企信通讯录变动后，会给指定的服务器发送通知，但是一个企信有多个应用服务，我想把这个通知转发给多个应用的服务，有什么好方式吗？

**Comment by laomu1988** [comment]
本插件不支持，可以参考src/middleware/load.js自己实现下

**Comment by YSHIDM** [comment]
用 mq 广播
