### ISSUE TITLE
静态资源问题

### ISSUE THREAD

**Issue by leeziiAtCn** [laomu1988/koa2-proxy#3]
![image 1](https://user-images.githubusercontent.com/22995117/30730190-ca8879f4-9f97-11e7-94cc-a4223584bef0.png)

代码如上图
![image 5](https://user-images.githubusercontent.com/22995117/30730212-f6cb7bec-9f97-11e7-97b2-5ce7434c0a49.png)

 

![image 3](https://user-images.githubusercontent.com/22995117/30730233-2202eb60-9f98-11e7-9267-d0dfb97de56f.png)

**Comment by laomu1988** [comment]
1.  最前面text/plain的问题， 我这边测试最最新版响应的header的content-Type是text/css， 你可以查看下你的是否是这样， 可以试着更新下koa2-proxy。
![1](https://user-images.githubusercontent.com/6356903/30730522-4d60ceb0-9f9a-11e7-8f32-c1a4a9c85859.png)

2. koa2-proxy不是koa的一个中间件， 是一个单独的代理服务， 只做中转转发。。你这里还有其他路由，包含这些服务的话建议使用 https://github.com/koajs/koa/wiki 中的中间件。
