### ISSUE TITLE
https 协议不支持

### ISSUE THREAD

**Issue by jane-** [laomu1988/koa2-proxy#4]
proxy.when(/api(.*)/, function(ctx) {
  ctx.request.host = 'ceshi.api.vipsouq.net';
  ctx.request.protocol = 'https';
  ctx.request.method = 'post';
  var url = ctx.request.url;
  // ctx.request.path="/api.php";

  if(url=='/api/gate/v1/userExpandInfo/updateHeadPortrait'){
    var  fileName = '100.jpg'
    ctx.request.header['content-type']='form-data';
    ctx.request.header['Content-Disposition']='attachment; filename=00.jpg'
    console.log(ctx.request.header['Content-Disposition']);
  }else{
    ctx.request.header['content-type']='form-data';
  }
我这样子写之后，转发没有加上https 默认还是http
load_remote: http://ceshi.api.vipsouq.net/api/gate/home/content

**Comment by laomu1988** [comment]
https未生效是因为protocol修改没有生效， 刚刚已修复（1.1.6版本），请更新
