### ISSUE TITLE
content-type类型的问题虽然设置了，但是发到服务器的还是from类型

### ISSUE THREAD

**Issue by jane-** [laomu1988/koa2-proxy#5]
不好意思还是这个问题， 我虽然设置了 ctx.request.header['content-type'] = 'application/json';但是发送到服务器上还是form类型
proxy.when(/api(.*)/, function(ctx) {

https://www.googleapis.com/qpxExpress/v1/trips/search?key=myApiKey
ctx.request.host = 'www.googleapis.com';

ctx.request.path="//qpxExpress/v1/trips/search"
ctx.request.querystring="key=myApiKey"
ctx.request.protocol = 'https';
ctx.request.header['content-type'] = 'application/json';
ctx.request.body={
"request": {
"slice": [
{
"origin": "ZRH",
"destination": "DUS",
"date": "2014-12-02"
}
],
"passengers": {
"adultCount": 1,
"infantInLapCount": 0,
"infantInSeatCount": 0,
"childCount": 0,
"seniorCount": 0
},
"solutions": 2,
"refundable": false
}
}
// var url = ctx.request.url;
// ctx.request.host = 'www.appollo.h5.me:8081';
// ctx.request.method = 'post';
// ctx.request.path="/api/"
// // console.log( ctx.request)
// ctx.request.querystring="url=https://ceshi.api.vipsouq.net"+url
// // ctx.request.protocol = 'https';
//
// // console.log(ctx,"99999**", ctx.request.body);
});

接口的报错  
"This API does not support parsing form-encoded input."
麻烦你看看

**Comment by laomu1988** [comment]
暂时未处理json格式，等晚上我看看

**Comment by jane-** [comment]
多谢

**Comment by jane-** [comment]
load.js  58行    fs.createReadScream(file.path), 是不是写错了，没有这个方法 我查了下文档 createReadStream 是这个

**Comment by laomu1988** [comment]
是写错了 😂

**Comment by laomu1988** [comment]
试试1.1.7版本的json格式，load.js也修改了  @jane-

**Comment by jane-** [comment]
可以了，多谢。  我今天也看了下你的源码，但是没有看懂， 不知道有没有这个荣幸请你指点一下，是否能加我微信 931702022

**Comment by laomu1988** [comment]
代理远程请求只是使用了[request](https://www.npmjs.com/package/request)模块， 把请求或者覆盖的内容按照request的参数要求组装后发送出去。。具体代码在/src/middleware/load.js中
