### ISSUE TITLE
定义post方法，但是服务器那边却不是post

### ISSUE THREAD

**Issue by jane-** [laomu1988/koa2-proxy#6]
ctx.request.method = 'post';
  ctx.request.host = 'ceshi.api.vipsouq.net';
  ctx.request.protocol = 'https';

  ctx.request.path="/api";
  var url = ctx.request.url;
  if(url=='/api/gate/v1/userExpandInfo/updateHeadPortrait'){
    ctx.request.header['content-type']='form-data';
  }else{
    ctx.request.header['content-type']='application/json';
  }
上次好的那个代码忘记保存了， 但是一段时间没有看了， 今天看了下服务器报错  Request method 'POST' not supported

**Comment by jane-** [comment]
响应头信息有allow 字段，是不是表示我不能发送post请求，怎么修改呢， 我发现我不用代理是正确的，用了代理，就呈现了allow字段
allow:HEAD, GET
connection:keep-alive
content-length:208
content-type:application/json;charset=UTF-8
date:Tue, 28 Nov 2017 04:51:51 GMT
server:Tengine/2.1.2
x-application-context:appollo-zuul-service:test:9040
X-Response-Time:48ms

**Comment by laomu1988** [comment]
header表示只能用只能get方法， 这不是代理的原因。不用代理的时候请求方式是post的么，明显你这里用代理将请求方法改成post了
