### ISSUE TITLE
关于使用上的..假如我想在Koa里使用这个..

### ISSUE THREAD

**Issue by Zephylaci** [laomu1988/koa2-proxy#7]
我想在一个基于koa2的页面里..访问指定的页面通过这个去做代理怎么做？
比如说我现在在：127.0.0.1:8080上启了个koa
我想在 127.0.0.1:8080/proxy/text 这里用这个proxy代理访问127.0.0.1:8082 
也就是说把when方法作为Koa的中间件来使用..我该怎么调用？

**Comment by Zephylaci** [comment]
顺便的我还想问下..能动态设置么..比如最开始没有用when挂东西..
之后用when挂了一个..
试了下..无效..
找了一圈也没看见koa有停止服务或者取消监听的函数....

**Comment by laomu1988** [comment]
koa2-proxy不是koa的一个中间件，他是完全独立的，内部已经使用了koa，可以看示例代码。另外未提供停止监听的方法
