### ISSUE TITLE
静态资源 mp3,mp4文件不能正确解析

### ISSUE THREAD

**Issue by hetanhong12345** [laomu1988/koa2-proxy#9]
![image](https://user-images.githubusercontent.com/11623055/47281539-2eed7400-d60e-11e8-9b25-c890a1ade0bd.png)
少了一个字段 Content-Range:所以不能正确解析 mp3,mp4等文件

![image](https://user-images.githubusercontent.com/11623055/47281637-87247600-d60e-11e8-8c6c-09c304fc3383.png)

**Comment by laomu1988** [comment]
不考虑支持断点续传
